# Generated by Django 4.2.6 on 2023-10-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
