# Generated by Django 4.2.6 on 2023-10-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0002_chatuser_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='interests',
            field=models.CharField(blank=True, choices=[('machine_learning', 'Machine Learning'), ('ai', 'Artificial Intelligence'), ('hiking', 'Hiking'), ('guitar', 'Playing Guitar')], max_length=20),
        ),
    ]
