# Generated by Django 4.2.6 on 2023-12-22 10:44

import USERS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0003_chatuser_bio_chatuser_city_chatuser_country_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='chatuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='chatuser',
            name='hide_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('do not show', 'DO_NOT_SHOW')], max_length=11),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default=USERS.models.get_default_profile_picture, max_length=255, null=True, upload_to=USERS.models.get_profile_picture),
        ),
    ]
