# Generated by Django 4.2.6 on 2026-04-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0004_alter_chatuser_managers_chatuser_hide_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatuser',
            name='hide_email',
        ),
        migrations.RemoveField(
            model_name='chatuser',
            name='is_email_verified',
        ),
        migrations.AddField(
            model_name='chatuser',
            name='recovery_key_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='recovery_key_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='interests',
            field=models.CharField(blank=True, choices=[('machine_learning', 'Machine Learning'), ('ai', 'Artificial Intelligence'), ('hiking', 'Hiking'), ('guitar', 'Playing Guitar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
