# Generated by Django 4.2.6 on 2026-04-21 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0005_step1_email_nullable_recovery_key_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatuser',
            name='email',
        ),
    ]
