# Generated by Django 4.2.6 on 2024-04-07 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CHAT_ROOMS', '0002_rename_chatroom_publicchatroom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('timestamp',)},
        ),
    ]
