# Generated by Django 4.2.6 on 2024-04-13 08:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CHAT_ROOMS', '0003_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicchatroom',
            name='for_friends_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicchatroom',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicchatroom',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='group_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
