# Generated by Django 4.2.6 on 2024-04-13 08:54

import CHAT_ROOMS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHAT_ROOMS', '0004_publicchatroom_for_friends_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicchatroom',
            name='room_picture',
            field=models.ImageField(blank=True, default=CHAT_ROOMS.models.get_default_room_picture, max_length=255, null=True, upload_to=CHAT_ROOMS.models.get_room_picture),
        ),
    ]
